

name: ci

on:
  push:
    branches:
      - main

jobs:
  smartcharger_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=steintokvam/smartcharger:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smartcharger:latest
          build-args: PROFILE=steintokvam

